---
version: '3.8'
services:
    maven:
      build: .
      container_name: mvn
      volumes:
        - data:/home/app/OldJavaApp/target/
    mongodb:
      build: .
      container_name: mongodb
      environment:
        - TZ=Europe/Moscow
        - MONGO_INITDB_DATABASE=mongodb
        - MONGO_INITDB_ROOT_USERNAME=mongouser
        - MONGO_INITDB_ROOT_PASSWORD=,mongopassword
      restart: always

    tomcat:
      build: .
      container_name: tom
      ports:
        - "8080:8080"
      volumes:
        - data:/usr/local/tomcat/webapps/
volumes:
  data:


